# filepath: .github/workflows/daily_crawler.yml

name: Daily VnExpress Crawler

on:
  workflow_dispatch: # Cho phép chạy thủ công từ tab Actions trên GitHub
  schedule:
    # Chạy vào 23:30 mỗi ngày (giờ Việt Nam)
    # 16:30 UTC tương đương 23:30 giờ Việt Nam (UTC+7)
    - cron: '30 16 * * *'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # --- CACHING CHO THƯ VIỆN PIP ---
    - name: Cache Pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # --- CACHING CHO TRÌNH DUYỆT PLAYWRIGHT ---
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Luôn cài đặt từ requirements.txt, không cần if/else nữa
        pip install -r requirements.txt
        # Cài đặt trình duyệt cho Playwright
        python -m playwright install

    - name: Run the crawler script
      env:
        # Sử dụng các secrets đã tạo
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python main.py